default against_notify = NotifyEx(msg=__("Is against a love affair with you"), img="/images_tool/icon/notification/emblems-against.webp")
default fear_against_notify = NotifyEx(msg=__("Has too much fear of you for a love affair"), img="/images_tool/icon/notification/relations-fear.webp")
# Characteristics
default increase_energy_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Energy"), img="/images_tool/icon/notification/characteristics-energy.webp")
default decrease_energy_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Energy"), img="/images_tool/icon/notification/characteristics-energy.webp")
default increase_willpower_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Willpower"), img="/images_tool/icon/notification/characteristics-willpower.webp")
default decrease_willpower_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Willpower"), img="/images_tool/icon/notification/characteristics-willpower.webp")
default increase_inhibition_notify = NotifyEx(msg=__("{color=#f00}{b}+{/b} Inhibition"), img="/images_tool/icon/notification/characteristics-inhibition.webp")
default decrease_inhibition_notify = NotifyEx(msg=__("{color=#00ff00} {b}-{/b} Inhibition"), img="/images_tool/icon/notification/characteristics-inhibition.webp")
default increase_addiction_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Addictions"), img="/images_tool/icon/notification/characteristics-addiction.webp")
default decrease_addiction_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Addictions"), img="/images_tool/icon/notification/characteristics-addiction.webp")
default increase_lust_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Lust"), img="/images_tool/icon/notification/characteristics-lust.webp")
default decrease_lust_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Lust"), img="/images_tool/icon/notification/characteristics-lust.webp")
# Relations
default increase_friendship_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Friendship"), img="/images_tool/icon/notification/relations-friendship.webp")
default decrease_friendship_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Friendship"), img="/images_tool/icon/notification/relations-friendship.webp")
default increase_favour_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Favour"), img="/images_tool/icon/notification/relations-favour.webp")
default decrease_favour_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Favour"), img="/images_tool/icon/notification/relations-favour.webp")
default increase_love_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Love"), img="/images_tool/icon/notification/relations-love.webp")
default decrease_love_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Love"), img="/images_tool/icon/notification/relations-love.webp")
default increase_corruption_notify = NotifyEx(msg=__("{color=#00ff00}{b}+{/b} Corruption"), img="/images_tool/icon/notification/relations-corruption.webp")
default decrease_corruption_notify = NotifyEx(msg=__("{color=#f00} {b}-{/b} Corruption"), img="/images_tool/icon/notification/relations-corruption.webp")
default increase_anger_notify = NotifyEx(msg=__("{color=#f00}{b}+{/b} Anger"), img="/images_tool/icon/notification/relations-anger.webp")
default decrease_anger_notify = NotifyEx(msg=__("{color=#00ff00} {b}-{/b} Anger"), img="/images_tool/icon/notification/relations-anger.webp")
default increase_fear_notify = NotifyEx(msg=__("{color=#f00}{b}+{/b} Fear"), img="/images_tool/icon/notification/relations-fear.webp")
default decrease_fear_notify = NotifyEx(msg=__("{color=#00ff00} {b}-{/b} Fear"), img="/images_tool/icon/notification/relations-fear.webp")
